# base_image is define in peerbook/Dockerfile
# to build base_image run from peerbook:
# docker build -t base_image .
FROM base_image

ENV LAYER_NAME=""

RUN apt-get update && apt-get install -y curl && \
    curl -o chamber -LOs https://github.com/segmentio/chamber/releases/download/v2.10.6/chamber-v2.10.6-linux-amd64 && \
    chmod 755 chamber && \
    mv chamber /usr/local/bin && \
    chamber version

CMD ["chamber","exec","${LAYER_NAME}","--","/app/server"]